#!/bin/sh

case `uname -s` in
    FreeBSD)
		glibtoolize
    aclocal19
    autoheader259
    automake19 --add-missing --foreign --copy
    autoconf259
    ;;

    *)
		glibtoolize
    aclocal
    autoheader
    automake --add-missing --foreign --copy
    autoconf
    ;;
esac
